// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqS8AxeGzGLvJsy6-kDQSMX8rypONQJQs',
    appId: '1:1050238939758:web:fe3420885df65544072c7f',
    messagingSenderId: '1050238939758',
    projectId: 'fir-demo-b82b6',
    authDomain: 'fir-demo-b82b6.firebaseapp.com',
    storageBucket: 'fir-demo-b82b6.appspot.com',
    measurementId: 'G-PEXE4K49HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqth5D0-3D4Ii7BhIBCnI81S4V5I2BQsA',
    appId: '1:1050238939758:android:d1fbf5d7b0130528072c7f',
    messagingSenderId: '1050238939758',
    projectId: 'fir-demo-b82b6',
    storageBucket: 'fir-demo-b82b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyU-YCiN1IKfdAzsIa9QL75rVWdlAObzc',
    appId: '1:1050238939758:ios:7d7a9b93cb48dd11072c7f',
    messagingSenderId: '1050238939758',
    projectId: 'fir-demo-b82b6',
    storageBucket: 'fir-demo-b82b6.appspot.com',
    iosClientId: '1050238939758-2ibcfde51f9n419c7fgjdvh7584hjhr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebassapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyU-YCiN1IKfdAzsIa9QL75rVWdlAObzc',
    appId: '1:1050238939758:ios:7d7a9b93cb48dd11072c7f',
    messagingSenderId: '1050238939758',
    projectId: 'fir-demo-b82b6',
    storageBucket: 'fir-demo-b82b6.appspot.com',
    iosClientId: '1050238939758-2ibcfde51f9n419c7fgjdvh7584hjhr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebassapp',
  );
}
